[package]
name = "serialize_macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"   # Parsing struct
quote = "1.0" # Inside quote write code will compile but it will not execute
