[package]
name = "serialize_macro_traits"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
syn = "2.0" # It help parsing the struct
quote = "1.0" # It help to write code in compile time but it will not execute it.